/**
 * bugtracker REST API
 * API to make a lot of money!
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@bugtracker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserRegistrationDto { 
    email?: string;
    firstName?: string;
    lastName?: string;
    password?: string;
    passwordConfirmation?: string;
}

