/**
 * bugtracker REST API
 * API to make a lot of money!
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@bugtracker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BugEntryReportingDto } from '../model/bugEntryReportingDto';
import { ResponseEntity } from '../model/responseEntity';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class BugEntryReportingControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * bugEntryReporting
     * 
     * @param bugEntryReportingDto bugEntryReportingDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public bugEntryReportingUsingPOST(bugEntryReportingDto: BugEntryReportingDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public bugEntryReportingUsingPOST(bugEntryReportingDto: BugEntryReportingDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public bugEntryReportingUsingPOST(bugEntryReportingDto: BugEntryReportingDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public bugEntryReportingUsingPOST(bugEntryReportingDto: BugEntryReportingDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (bugEntryReportingDto === null || bugEntryReportingDto === undefined) {
            throw new Error('Required parameter bugEntryReportingDto was null or undefined when calling bugEntryReportingUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseEntity>(`${this.configuration.basePath}/bugEntryReporting/`,
            bugEntryReportingDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
