/**
 * bugtracker REST API
 * API to make a lot of money!
 *
 * The version of the OpenAPI document: 1.0
 * Contact: info@bugtracker.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ResponseEntity } from '../model/responseEntity';
import { UserAuthenticationDto } from '../model/userAuthenticationDto';
import { UserChangePasswordDto } from '../model/userChangePasswordDto';
import { UserDto } from '../model/userDto';
import { UserPasswordResetDto } from '../model/userPasswordResetDto';
import { UserPasswordResetRequestDto } from '../model/userPasswordResetRequestDto';
import { UserRegistrationDto } from '../model/userRegistrationDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class UserControllerService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * authentication
     * 
     * @param userAuthenticationDto userAuthenticationDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authenticationUsingPOST(userAuthenticationDto: UserAuthenticationDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public authenticationUsingPOST(userAuthenticationDto: UserAuthenticationDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public authenticationUsingPOST(userAuthenticationDto: UserAuthenticationDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public authenticationUsingPOST(userAuthenticationDto: UserAuthenticationDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userAuthenticationDto === null || userAuthenticationDto === undefined) {
            throw new Error('Required parameter userAuthenticationDto was null or undefined when calling authenticationUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.configuration.basePath}/api/users/authentication`,
            userAuthenticationDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * changePassword
     * 
     * @param userChangePasswordDto userChangePasswordDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changePasswordUsingPOST(userChangePasswordDto: UserChangePasswordDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public changePasswordUsingPOST(userChangePasswordDto: UserChangePasswordDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public changePasswordUsingPOST(userChangePasswordDto: UserChangePasswordDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public changePasswordUsingPOST(userChangePasswordDto: UserChangePasswordDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userChangePasswordDto === null || userChangePasswordDto === undefined) {
            throw new Error('Required parameter userChangePasswordDto was null or undefined when calling changePasswordUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseEntity>(`${this.configuration.basePath}/api/users/changePassword`,
            userChangePasswordDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentUser
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentUserUsingGET(observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public getCurrentUserUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public getCurrentUserUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public getCurrentUserUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<UserDto>(`${this.configuration.basePath}/api/users/current`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Resets password
     * 
     * @param userPasswordResetDto userPasswordResetDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public passwordResetUsingPOST(userPasswordResetDto: UserPasswordResetDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public passwordResetUsingPOST(userPasswordResetDto: UserPasswordResetDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public passwordResetUsingPOST(userPasswordResetDto: UserPasswordResetDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public passwordResetUsingPOST(userPasswordResetDto: UserPasswordResetDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userPasswordResetDto === null || userPasswordResetDto === undefined) {
            throw new Error('Required parameter userPasswordResetDto was null or undefined when calling passwordResetUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseEntity>(`${this.configuration.basePath}/api/users/passwordReset`,
            userPasswordResetDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * registerUser
     * 
     * @param userRegistrationDto userRegistrationDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerUserUsingPOST(userRegistrationDto: UserRegistrationDto, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public registerUserUsingPOST(userRegistrationDto: UserRegistrationDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public registerUserUsingPOST(userRegistrationDto: UserRegistrationDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public registerUserUsingPOST(userRegistrationDto: UserRegistrationDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userRegistrationDto === null || userRegistrationDto === undefined) {
            throw new Error('Required parameter userRegistrationDto was null or undefined when calling registerUserUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<UserDto>(`${this.configuration.basePath}/api/users/register`,
            userRegistrationDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Request password reset token
     * 
     * @param userPasswordResetRequestDto userPasswordResetRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public requestPasswordResetUsingPOST(userPasswordResetRequestDto: UserPasswordResetRequestDto, observe?: 'body', reportProgress?: boolean): Observable<ResponseEntity>;
    public requestPasswordResetUsingPOST(userPasswordResetRequestDto: UserPasswordResetRequestDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseEntity>>;
    public requestPasswordResetUsingPOST(userPasswordResetRequestDto: UserPasswordResetRequestDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseEntity>>;
    public requestPasswordResetUsingPOST(userPasswordResetRequestDto: UserPasswordResetRequestDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userPasswordResetRequestDto === null || userPasswordResetRequestDto === undefined) {
            throw new Error('Required parameter userPasswordResetRequestDto was null or undefined when calling requestPasswordResetUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (basicAuth) required
        if (this.configuration.username || this.configuration.password) {
            headers = headers.set('Authorization', 'Basic ' + btoa(this.configuration.username + ':' + this.configuration.password));
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ResponseEntity>(`${this.configuration.basePath}/api/users/passwordResetRequest`,
            userPasswordResetRequestDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
